#!/usr/bin/env python3
"""Run the chapter's 11 puzzles x seeds 1-20 in Python and report, as
tests/chapter-runs.lisp does for the SBCL port (loop0002 item 13).

    python3 python/scripts/chapter_runs.py           # print the report
    python3 python/scripts/chapter_runs.py --write   # update python/RESULTS.md
    python3 python/scripts/chapter_runs.py --check   # exit 1 if it is stale

Every run is harness.run_config(puzzle, seed=s, max_iterations=20000), in a
fresh World (Python is always in oracle mode: the shared RNG, double floats).
The runs are spread over a process pool (a few seconds in all).  Outcomes:
  valid    "Done :" and solution_checker accepts the decomposition
  invalid  "Done :" but the checker rejects it (the kill-block gap)
  gave-up  the coderack was empty after the retry (start.lisp (return))
  capped   still running at 20000 iterations
  error    a Lisp error (the reactivate-cyto race)

`report(records)` makes the generated part of python/RESULTS.md from run
records ({"problem", "seed", "outcome", "iterations", "check"}); the full-run
test (python/tests/test_full_runs.py) feeds it the oracle's records and
checks python/RESULTS.md against them.
"""

import concurrent.futures
import fractions
import io
import os
import pathlib
import re
import sys

PYTHON_DIR = pathlib.Path(__file__).resolve().parent.parent
if str(PYTHON_DIR) not in sys.path:
    sys.path.insert(0, str(PYTHON_DIR))

RESULTS_MD = PYTHON_DIR / "RESULTS.md"
BEGIN = "<!-- begin: generated by python/scripts/chapter_runs.py -->"
END = "<!-- end: generated by python/scripts/chapter_runs.py -->"

SEEDS = 20
CAP = 20000

# (number target bricks chapter-says), tests/chapter-runs.lisp's *puzzles*
PUZZLES = [
    (1, 114, (11, 20, 7, 1, 6), "sample run (Fig. III-3) ends 20 x 6 - (7 - 1); also (20 - 1) x 6"),
    (2, 87, (8, 3, 9, 10, 7), "human data only: 8 x 10 + 7, 9 x 10 - 3"),
    (3, 31, (3, 5, 24, 3, 14), "Numbo did not solve it (Fig. III-6); four solutions exist"),
    (4, 25, (8, 5, 5, 11, 2), "human data only: 5 x 5"),
    (5, 102, (6, 17, 2, 4, 1), "human data only: 6 x 17"),
    (6, 146, (12, 2, 5, 7, 18), "human data only: 12 x (5 + 7) + 2"),
    (7, 6, (3, 3, 17, 11, 22), "Numbo immediately gives 3 + 3"),
    (8, 11, (2, 5, 1, 25, 23), "Numbo immediately gives 2 x 5 + 1"),
    (9, 116, (20, 2, 16, 14, 6), "Numbo finds 6 x 20 - 2 - (16 - 14)"),
    (10, 127, (6, 4, 22, 5, 7), "once in a while 6 x 5, then 4 x 30 + 7"),
    (11, 41, (5, 16, 22, 25, 1), "Numbo has problems: nearly random search"),
]


def median(xs):
    """chapter-runs.lisp: median (CL ROUND of the two middle values' mean,
    half to even, for an even count)."""
    if not xs:
        return None
    v = sorted(xs)
    n = len(v)
    if n % 2:
        return v[n // 2]
    return round(fractions.Fraction(v[n // 2 - 1] + v[n // 2], 2))


# --- canonical solutions: chapter-runs.lisp's expr-tokens ... canonical-solution

def expr_tokens(s):
    tokens, i = [], 0
    while i < len(s):
        c = s[i]
        if c == " ":
            i += 1
        elif c in "()+-x/":
            tokens.append(c)
            i += 1
        elif c.isdigit():
            j = i
            while j < len(s) and s[j].isdigit():
                j += 1
            tokens.append(int(s[i:j]))
            i = j
        else:
            raise ValueError(f"expr-tokens: {c!r} in {s!r}")
    return tokens


def parse_expr(tokens):
    """TOKENS = term op term | term.  Returns (tree, rest)."""
    def term(ts):
        if ts and ts[0] == "(":
            e, rest = parse_expr(ts[1:])
            return e, rest[1:]  # drop ")"
        return ts[0], ts[1:]

    a, rest = term(tokens)
    if rest and rest[0] in ("+", "-", "x", "/"):
        b, rest2 = term(rest[1:])
        return [rest[0], a, b], rest2
    return a, rest


def expr_value(e):
    if isinstance(e, int):
        return e
    a, b = expr_value(e[1]), expr_value(e[2])
    return {"+": lambda: a + b, "-": lambda: a - b, "x": lambda: a * b,
            "/": lambda: fractions.Fraction(a, b)}[e[0]]()


def expr_string(e, top):
    if isinstance(e, int):
        return str(e)
    s = f"{expr_string(e[1], False)} {e[0]} {expr_string(e[2], False)}"
    return s if top else f"({s})"


def canonical(e):
    if isinstance(e, int):
        return e
    a, b = canonical(e[1]), canonical(e[2])
    if e[0] in ("+", "x") and (expr_value(a) < expr_value(b)
                               or (expr_value(a) == expr_value(b)
                                   and expr_string(a, True) < expr_string(b, True))):
        a, b = b, a
    return [e[0], a, b]


def canonical_solution(s):
    """"114 = (20 x 6) - (7 - 1)" => the same with + and x operands ordered,
    larger first."""
    target, _, expr = s.partition(" = ")
    return f"{target} = {expr_string(canonical(parse_expr(expr_tokens(expr))[0]), True)}"


# --- runs and report ------------------------------------------------------------

def classify(record):
    if record["outcome"] == "solved":
        return "valid" if record["check"][0] else "invalid"
    return record["outcome"]


def report(records):
    """The tables (chapter-runs.lisp: report) for RECORDS, the runs of every
    puzzle x seeds 1-SEEDS."""
    by_run = {(tuple(r["problem"]), r["seed"]): r for r in records}
    lines = ["| # | Target | Bricks | valid | invalid Done | gave up | capped | error "
             "| iterations to a valid solution (median / min-max) |",
             "|---|---|---|---|---|---|---|---|---|"]
    paragraphs = []
    for num, target, bricks, says in PUZZLES:
        counts = dict.fromkeys(["valid", "invalid", "gave-up", "capped", "error"], 0)
        iterations, expressions, valid_seeds = [], [], []
        for seed in range(1, SEEDS + 1):
            r = by_run[((target, *bricks), seed)]
            outcome = classify(r)
            counts[outcome] += 1
            if outcome == "valid":
                iterations.append(r["iterations"])
                valid_seeds.append(seed)
                key = canonical_solution(r["check"][2])
                cell = next((c for c in expressions if c[0] == key), None)
                if cell:
                    cell[1] += 1
                else:
                    expressions.insert(0, [key, 1])  # push
        expressions.sort(key=lambda c: -c[1])  # stable, as SBCL's list sort
        its = (f"{median(iterations)} / {min(iterations)}-{max(iterations)}"
               if iterations else "-")
        lines.append(f"| {num} | {target} | {' '.join(map(str, bricks))} "
                     f"| {counts['valid']}/{SEEDS} | {counts['invalid']} | {counts['gave-up']} "
                     f"| {counts['capped']} | {counts['error']} | {its} |")
        para = [f"**#{num} ({target})** — chapter: {says}."]
        if expressions:
            para.append("Valid solutions found (count): "
                        + "; ".join(f"`{k}` ({n})" for k, n in expressions) + ".")
            para.append(f"Seeds: {' '.join(map(str, valid_seeds))}; "
                        f"iterations: {' '.join(map(str, iterations))}.")
        else:
            para.append("No valid solution.")
        paragraphs.append("\n".join(para))
    return "\n".join(lines) + "\n\n" + "\n\n".join(paragraphs) + "\n"


def python_run(spec):
    from numbo import harness, solution_checker

    problem, seed = spec
    out = io.StringIO()
    result = harness.run_config(list(problem), seed=seed, max_iterations=CAP, out=out)
    return {"problem": list(problem), "seed": seed, "outcome": result["outcome"],
            "iterations": result["iterations"],
            "check": list(solution_checker.check_solution(out.getvalue(), list(problem)))}


def run_python(jobs=None):
    specs = [((target, *bricks), seed) for _, target, bricks, _ in PUZZLES
             for seed in range(1, SEEDS + 1)]
    with concurrent.futures.ProcessPoolExecutor(max_workers=jobs or os.cpu_count()) as pool:
        return list(pool.map(python_run, specs))


def generated_section(text):
    """The generated part of RESULTS.md's TEXT (between the markers)."""
    m = re.search(re.escape(BEGIN) + r"\n(.*?)" + re.escape(END), text, re.S)
    if not m:
        raise ValueError("RESULTS.md has no generated section")
    return m.group(1)


def main(argv):
    import argparse

    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    g = p.add_mutually_exclusive_group()
    g.add_argument("--write", action="store_true", help="update python/RESULTS.md")
    g.add_argument("--check", action="store_true", help="exit 1 if python/RESULTS.md is stale")
    p.add_argument("--jobs", type=int, default=None)
    args = p.parse_args(argv)
    text = report(run_python(args.jobs))
    if args.write:
        old = RESULTS_MD.read_text()
        new = old.replace(BEGIN + "\n" + generated_section(old) + END, BEGIN + "\n" + text + END)
        RESULTS_MD.write_text(new)
        print(f"wrote {RESULTS_MD}")
    elif args.check:
        if generated_section(RESULTS_MD.read_text()) != text:
            print("python/RESULTS.md is out of date: run python3 python/scripts/chapter_runs.py --write")
            return 1
        print("python/RESULTS.md is up to date")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
