#!/usr/bin/env python3
"""Generate the Pnet tables of python/numbo/pnet_def.py from src/pnet-def.lisp.

Usage: python3 python/scripts/gen_pnet_def.py [--check]

Reads init-pnet's 91 (setq HOLDER (make-instance 'pnode :key value ...))
forms and the top-level (setq *pnet* (list ...)), and rewrites the part of
pnet_def.py between the "BEGIN GENERATED" and "END GENERATED" lines: the
table INIT_PNET (holders and init keywords in source order) and PNET.  With
--check it changes nothing and exits 1 if the file is not what it would
write (python/tests/test_pnet_def.py runs this).

The reader is the small subset of the Lisp reader pnet-def.lisp needs:
comments, lists, quote, strings, integers and symbols (upcased, as SBCL's
standard readtable reads them).  It refuses anything else.
"""

import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
SOURCE = REPO / "src" / "pnet-def.lisp"
TARGET = REPO / "python" / "numbo" / "pnet_def.py"
BEGIN = "# --- BEGIN GENERATED by python/scripts/gen_pnet_def.py from src/pnet-def.lisp ---\n"
END = "# --- END GENERATED ---\n"

TOKEN = re.compile(r"""\s+|;[^\n]*|(\()|(\))|(')|"((?:[^"\\]|\\.)*)"|([^\s()'";]+)""")


class Sym(str):
    """A symbol read from the source (its upper-case name)."""


class Quote:
    def __init__(self, form):
        self.form = form


def read_all(text):
    stack = [[]]
    quotes = [[]]   # per level: positions waiting for a quoted form
    pos = 0
    while pos < len(text):
        m = TOKEN.match(text, pos)
        if not m:
            raise SyntaxError(f"cannot read at {text[pos:pos + 30]!r}")
        pos = m.end()
        lparen, rparen, quote, string, atom = m.groups()
        if lparen:
            stack.append([])
            quotes.append([])
            continue
        if quote:
            quotes[-1].append(len(stack[-1]))
            continue
        if rparen:
            if quotes[-1]:
                raise SyntaxError("quote before )")
            form = stack.pop()
            quotes.pop()
        elif string is not None:
            if "\\" in string:
                raise SyntaxError(f"escape in string {string!r}")
            form = string
        elif atom is not None:
            if re.fullmatch(r"[+-]?\d+", atom):
                form = int(atom)
            elif re.fullmatch(r"[a-z0-9+\-*/%<>=!?_.:]+", atom, re.I) and "." != atom \
                    and not re.fullmatch(r"[+-]?\d*\.\d*(e[+-]?\d+)?", atom, re.I):
                form = Sym(atom.upper())
            else:
                raise SyntaxError(f"unsupported atom {atom!r}")
        else:
            continue
        while quotes[-1] and quotes[-1][-1] == len(stack[-1]):
            quotes[-1].pop()
            form = Quote(form)
        stack[-1].append(form)
    if len(stack) != 1 or quotes[0]:
        raise SyntaxError("unbalanced input")
    return stack[0]


def constant(form):
    """The value of an init-pnet argument: a quoted form, a number or a string."""
    if isinstance(form, Quote):
        return form.form
    if isinstance(form, (int, str)) and not isinstance(form, Sym):
        return form
    raise ValueError(f"not a constant: {form!r}")


def python_literal(x):
    if isinstance(x, Sym):
        return f"_S({str(x)!r})"
    if isinstance(x, (int, str)):
        return repr(x) if not isinstance(x, str) else repr(str(x))
    if isinstance(x, list):
        return "[" + ", ".join(python_literal(v) for v in x) + "]"
    raise ValueError(f"no literal for {x!r}")


def init_pnet_entries(forms):
    defun = next(f for f in forms if isinstance(f, list) and f[:2] == ["DEFUN", "INIT-PNET"])
    entries = []
    for form in defun[3:]:
        setq, holder, make = form
        assert setq == "SETQ" and isinstance(holder, Sym), form
        assert make[0] == "MAKE-INSTANCE" and constant(make[1]) == "PNODE", make
        args = make[2:]
        assert len(args) % 2 == 0, holder
        init = []
        for key, value in zip(args[::2], args[1::2]):
            assert isinstance(key, Sym) and key.startswith(":"), key
            init.append((key[1:].lower().replace("-", "_"), constant(value)))
        entries.append((holder, init))
    return entries


def pnet_holders(forms):
    (form,) = [f for f in forms if isinstance(f, list) and f[:2] == ["SETQ", "*PNET*"]]
    assert form[2][0] == "LIST"
    return form[2][1:]


def generated_text():
    forms = read_all(SOURCE.read_text(encoding="utf-8"))
    lines = [BEGIN, "\n", "# init-pnet: (holder, [(init keyword, value), ...]), in source order.\n",
             "INIT_PNET = [\n"]
    for holder, init in init_pnet_entries(forms):
        lines.append(f"    (_S({str(holder)!r}), [\n")
        for key, value in init:
            if key == "neighbors":
                lines.append("        ('neighbors', [\n")
                for pair in value:
                    lines.append(f"            {python_literal(pair)},\n")
                lines.append("        ]),\n")
            else:
                lines.append(f"        ({key!r}, {python_literal(value)}),\n")
        lines.append("    ]),\n")
    lines.append("]\n\n# The top-level (setq *pnet* (list ...)): the 88 holders, in order.\n")
    lines.append("PNET = [\n")
    holders = pnet_holders(forms)
    for i in range(0, len(holders), 6):
        lines.append("    " + " ".join(f"_S({str(h)!r})," for h in holders[i:i + 6]) + "\n")
    lines.append("]\n\n" + END)
    return "".join(lines)


def main(argv):
    check = argv[1:] == ["--check"]
    if argv[1:] not in ([], ["--check"]):
        print(__doc__, file=sys.stderr)
        return 2
    current = TARGET.read_text(encoding="utf-8")
    start = current.index(BEGIN)
    end = current.index(END) + len(END)
    new = current[:start] + generated_text() + current[end:]
    if check:
        if new != current:
            print(f"{TARGET} is out of date: run python3 {pathlib.Path(__file__).name}")
            return 1
        return 0
    TARGET.write_text(new, encoding="utf-8")
    print(f"wrote {TARGET}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
