"""Shape checks for the Perl end-to-end baseline (tests/golden/e2e_baseline.json).

Mirrors: Seqsee/config/sequence_list_for_testing run through
lib/Test/Seqsee.pm (RunSeqsee) via oracle/e2e_run.perl; generated by
oracle/baseline.py. Later end-to-end tests compare the Python port against
these statistics.
"""
from pathlib import Path

import golden

REPO = Path(__file__).resolve().parents[2]
SEQ_LIST = REPO / "config" / "sequence_list_for_testing"
# TestOutputStatus values (lib/Seqsee/ResultOfTestRun.pm)
STATUSES = {"Successful", "RanOutOfTerms", "InitialBlemish", "ExtendedABit",
            "NotEvenExtended", "Crashed"}


def expected_sequences():
    out = []
    for line in SEQ_LIST.read_text().splitlines():
        if not line.strip():
            continue
        label, _, rest = line.rpartition(":")
        seq, cont = rest.split("|")
        out.append((label, " ".join(seq.split()), " ".join(cont.split())))
    return out


def test_baseline_covers_every_sequence_in_order():
    data = golden.load("e2e_baseline")
    assert [(d["label"], d["seq"], d["continuation"]) for d in data] == expected_sequences()


def test_baseline_entry_shape():
    for d in golden.load("e2e_baseline"):
        assert d["max_steps"] == 10000
        assert d["seeds"] == list(range(1, 11))
        n = len(d["seeds"])
        assert len(d["statuses"]) == len(d["steps"]) == n
        assert set(d["statuses"]) <= STATUSES
        assert all(isinstance(s, int) and 0 <= s <= d["max_steps"] for s in d["steps"])
        assert d["successes"] == d["statuses"].count("Successful")
        assert d["success_rate"] == d["successes"] / n
