(load "thematic-focus.ss")
(clear-tf)
(load "adj-setup.ss")
(adj-load)
(load "fonts.ss")
(load "drafter.ss")
(load "sugar.ss")
(load "draft-setup.ss")
(load "curve.ss")
(do-graf)
(load "scratchpad.ss")
(make-scratchpad)
(load "draw.ss")
(load "touching.ss")
(load "anticipate.ss")
(load "borrow.ss")
(load "loop.ss")
(load "scores.ss")
(set! *trained* 'nada)
