"""The Pnet: the pnode flavor and the 1987 network as data.

Port of src/pnet-def.lisp.  INIT_PNET and PNET below are generated from that
file by python/scripts/gen_pnet_def.py (don't edit them by hand), in the
source's order of nodes, init keywords and neighbors.
python/tests/test_pnet_def.py compares them with the oracle's dump,
python/fixtures/pnet.json.

The 1987 holder variables (node-1 ... times10-15, operand ... instance,
plus minus times) are global symbols whose values are the pnodes; the code
later gets a pnode from a symbol with (eval ...).  Here they are a registry,
a dict from the holder Symbol to its Pnode, which init_pnet fills; the World
of later items owns it.  The values in a pnode follow numbo.franz's model of
Lisp data: names and types are Symbols, short names are Lisp strings (str),
neighbors are lists of [pnode-symbol, link-type-symbol] until
initialize-pnet-2 (pnet_functions) replaces the symbols with pnodes, and
codelets are lists [function, threshold-symbol, urgency-symbol, args].
"""

import sys

from numbo.franz import Symbol, franz_pname
from numbo.franz import intern as _S

# defflavor pnode: the instance variables, in order (Lisp short-name is
# short_name, and so on).  Uninitialized ones are nil (flavors-compat.lisp).
SLOTS = (
    "activation",
    "spreadable_activation",
    "temp_activation_holder",
    "neighbors",
    "instances",
    "name",
    "type",
    "value",
    "codelets",
    "short_name",       # for graphics
    "x_region",
    "y_region",
    "x_box",
    "y_box",
    "x_act",
    "y_act",
    "x_name",
    "y_name",
    "old_boxsize",
)


class Pnode:
    """pnet-def.lisp: defflavor pnode (settable, inittable and gettable
    instance variables, so plain attributes).  The methods are in
    pnet_functions."""

    __slots__ = SLOTS

    def __init__(self, **init):
        for slot in SLOTS:
            setattr(self, slot, None)
        for slot, value in init.items():
            setattr(self, slot, value)

    def __repr__(self):
        return f"#<pnode {self.name!r}>"


def _copy_tree(x):
    """A copy of the list structure of X; atoms (Symbols included) are shared."""
    if isinstance(x, list):
        return [_copy_tree(v) for v in x]
    return x


def init_pnet(holders):
    """pnet-def.lisp: init-pnet.  Make the 91 pnodes and set each holder in
    the registry HOLDERS (a dict Symbol -> Pnode) to its pnode.

    The Lisp init arguments are quoted constants, shared by every call; one
    SBCL process calls init-pnet once, so each call here gets fresh copies,
    and a World's pnodes never share list structure with another's."""
    for holder, init in INIT_PNET:
        holders[holder] = Pnode(**{key: _copy_tree(value) for key, value in init})


def pnet_list(holders):
    """pnet-def.lisp: the top-level (setq *pnet* (list node-1 ...)).  The 88
    pnodes of *pnet*, in order: every holder's pnode except plus, minus and
    times."""
    return [holders[holder] for holder in PNET]


def _princ(x):
    """How SBCL's princ (format ~a) prints a pnode name or an activation:
    symbols with their upper-case names, doubles as 2.5d0."""
    if isinstance(x, Symbol):
        return x.name
    if x is None:
        return "NIL"
    return franz_pname(x)


def print_pnet_all(pnet, out=None):
    """pnet-def.lisp: print-pnet-all.  Print all the nodes and activations
    in PNET (*pnet*)."""
    out = out or sys.stdout
    for pnode in pnet:
        out.write(f"({_princ(pnode.name)} {_princ(pnode.activation)})")


def print_pnet(pnet, threshold, out=None):
    """pnet-def.lisp: print-pnet.  Print the nodes of PNET (*pnet*) whose
    activation is > THRESHOLD."""
    out = out or sys.stdout
    for pnode in pnet:
        if pnode.activation > threshold:
            out.write(f"({_princ(pnode.name)} {_princ(pnode.activation)})")


# --- BEGIN GENERATED by python/scripts/gen_pnet_def.py from src/pnet-def.lisp ---

# init-pnet: (holder, [(init keyword, value), ...]), in source order.
INIT_PNET = [
    (_S('NODE-1'), [
        ('value', 1),
        ('neighbors', [
            [_S('PLUS1-1'), _S('RESULT+')],
            [_S('PLUS1-2'), _S('RESULT+')],
            [_S('PLUS1-3'), _S('RESULT+')],
            [_S('PLUS1-4'), _S('RESULT+')],
            [_S('PLUS1-5'), _S('RESULT+')],
            [_S('PLUS1-6'), _S('RESULT+')],
            [_S('PLUS1-7'), _S('RESULT+')],
            [_S('PLUS1-8'), _S('RESULT+')],
            [_S('PLUS1-9'), _S('RESULT+')],
        ]),
        ('name', _S('ONE')),
        ('short_name', '1'),
        ('type', _S('NUM')),
    ]),
    (_S('NODE-2'), [
        ('value', 2),
        ('neighbors', [
            [_S('PLUS1-2'), _S('RESULT+')],
            [_S('PLUS2-2'), _S('RESULT+')],
            [_S('PLUS2-3'), _S('RESULT+')],
            [_S('PLUS2-4'), _S('RESULT+')],
            [_S('PLUS2-5'), _S('RESULT+')],
            [_S('PLUS2-6'), _S('RESULT+')],
            [_S('PLUS2-7'), _S('RESULT+')],
            [_S('PLUS2-8'), _S('RESULT+')],
            [_S('TIMES2-2'), _S('OPERAND')],
            [_S('TIMES2-3'), _S('OPERAND')],
            [_S('TIMES2-4'), _S('OPERAND')],
            [_S('TIMES2-5'), _S('OPERAND')],
            [_S('TIMES2-7'), _S('OPERAND')],
            [_S('TIMES2-10'), _S('OPERAND')],
            [_S('TIMES2-20'), _S('OPERAND')],
            [_S('TIMES2-12'), _S('OPERAND')],
            [_S('PLUS1-1'), _S('RESULT+')],
        ]),
        ('name', _S('TWO')),
        ('short_name', '2'),
        ('type', _S('NUM')),
    ]),
    (_S('NODE-3'), [
        ('value', 3),
        ('neighbors', [
            [_S('PLUS1-3'), _S('RESULT+')],
            [_S('PLUS2-3'), _S('RESULT+')],
            [_S('PLUS3-3'), _S('RESULT+')],
            [_S('PLUS3-4'), _S('RESULT+')],
            [_S('PLUS3-5'), _S('RESULT+')],
            [_S('PLUS3-6'), _S('RESULT+')],
            [_S('PLUS3-7'), _S('OPERAND')],
            [_S('TIMES2-3'), _S('OPERAND')],
            [_S('TIMES3-3'), _S('OPERAND')],
            [_S('TIMES3-10'), _S('OPERAND')],
            [_S('TIMES3-20'), _S('OPERAND')],
            [_S('PLUS1-2'), _S('RESULT+')],
            [_S('NODE-4'), _S('SIMILAR')],
        ]),
        ('name', _S('THREE')),
        ('short_name', '3'),
        ('type', _S('NUM')),
    ]),
    (_S('NODE-4'), [
        ('value', 4),
        ('neighbors', [
            [_S('PLUS1-4'), _S('RESULT+')],
            [_S('PLUS2-4'), _S('RESULT+')],
            [_S('PLUS3-4'), _S('RESULT+')],
            [_S('PLUS4-4'), _S('RESULT+')],
            [_S('PLUS4-5'), _S('RESULT+')],
            [_S('PLUS4-6'), _S('RESULT+')],
            [_S('TIMES2-4'), _S('OPERAND')],
            [_S('TIMES4-4'), _S('OPERAND')],
            [_S('TIMES4-10'), _S('OPERAND')],
            [_S('TIMES4-20'), _S('OPERAND')],
            [_S('PLUS1-3'), _S('RESULT+')],
            [_S('PLUS2-2'), _S('RESULT+')],
            [_S('TIMES2-2'), _S('RESULTX')],
            [_S('NODE-3'), _S('SIMILAR')],
            [_S('NODE-5'), _S('SIMILAR')],
        ]),
        ('name', _S('FOUR')),
        ('short_name', '4'),
        ('type', _S('NUM')),
    ]),
    (_S('NODE-5'), [
        ('value', 5),
        ('neighbors', [
            [_S('PLUS1-5'), _S('RESULT+')],
            [_S('PLUS2-5'), _S('RESULT+')],
            [_S('PLUS3-5'), _S('RESULT+')],
            [_S('PLUS4-5'), _S('RESULT+')],
            [_S('PLUS5-5'), _S('RESULT+')],
            [_S('PLUS5-10'), _S('RESULT+')],
            [_S('TIMES2-5'), _S('OPERAND')],
            [_S('TIMES5-5'), _S('OPERAND')],
            [_S('TIMES5-6'), _S('OPERAND')],
            [_S('TIMES5-10'), _S('OPERAND')],
            [_S('TIMES5-20'), _S('OPERAND')],
            [_S('PLUS1-4'), _S('RESULT+')],
            [_S('PLUS2-3'), _S('RESULT+')],
            [_S('NODE-4'), _S('SIMILAR')],
            [_S('NODE-6'), _S('SIMILAR')],
        ]),
        ('name', _S('FIVE')),
        ('short_name', '5'),
        ('type', _S('NUM')),
    ]),
    (_S('NODE-6'), [
        ('value', 6),
        ('neighbors', [
            [_S('PLUS1-6'), _S('RESULT+')],
            [_S('PLUS2-6'), _S('RESULT+')],
            [_S('PLUS3-6'), _S('RESULT+')],
            [_S('PLUS4-6'), _S('RESULT+')],
            [_S('PLUS1-5'), _S('RESULT+')],
            [_S('PLUS2-4'), _S('RESULT+')],
            [_S('PLUS3-3'), _S('RESULT+')],
            [_S('TIMES2-3'), _S('RESULTX')],
            [_S('TIMES5-6'), _S('OPERAND')],
            [_S('TIMES6-10'), _S('OPERAND')],
            [_S('NODE-5'), _S('SIMILAR')],
            [_S('NODE-7'), _S('SIMILAR')],
        ]),
        ('name', _S('SIX')),
        ('short_name', '6'),
        ('type', _S('NUM')),
    ]),
    (_S('NODE-7'), [
        ('value', 7),
        ('neighbors', [
            [_S('PLUS1-7'), _S('RESULT+')],
            [_S('PLUS2-7'), _S('RESULT+')],
            [_S('PLUS3-7'), _S('RESULT+')],
            [_S('PLUS7-8'), _S('RESULT+')],
            [_S('TIMES2-7'), _S('OPERAND')],
            [_S('TIMES7-7'), _S('OPERAND')],
            [_S('TIMES7-10'), _S('OPERAND')],
            [_S('PLUS1-6'), _S('RESULT+')],
            [_S('PLUS2-5'), _S('RESULT+')],
            [_S('PLUS3-4'), _S('RESULT+')],
            [_S('NODE-6'), _S('SIMILAR')],
            [_S('NODE-8'), _S('SIMILAR')],
        ]),
        ('name', _S('SEVEN')),
        ('short_name', '7'),
        ('type', _S('NUM')),
    ]),
    (_S('NODE-8'), [
        ('value', 8),
        ('neighbors', [
            [_S('PLUS1-8'), _S('RESULT+')],
            [_S('PLUS2-8'), _S('RESULT+')],
            [_S('PLUS1-7'), _S('RESULT+')],
            [_S('PLUS2-6'), _S('RESULT+')],
            [_S('PLUS3-5'), _S('RESULT+')],
            [_S('PLUS4-4'), _S('RESULT+')],
            [_S('PLUS7-8'), _S('RESULT+')],
            [_S('TIMES2-4'), _S('RESULT+')],
            [_S('TIMES8-10'), _S('OPERAND')],
            [_S('NODE-7'), _S('SIMILAR')],
            [_S('NODE-9'), _S('SIMILAR')],
        ]),
        ('name', _S('EIGHT')),
        ('short_name', '8'),
        ('type', _S('NUM')),
    ]),
    (_S('NODE-9'), [
        ('value', 9),
        ('neighbors', [
            [_S('PLUS1-9'), _S('RESULT+')],
            [_S('TIMES9-9'), _S('OPERAND')],
            [_S('TIMES9-10'), _S('OPERAND')],
            [_S('PLUS1-8'), _S('RESULT+')],
            [_S('PLUS2-7'), _S('RESULT+')],
            [_S('PLUS3-6'), _S('RESULT+')],
            [_S('PLUS4-5'), _S('RESULT+')],
            [_S('TIMES3-3'), _S('RESULTX')],
            [_S('NODE-8'), _S('SIMILAR')],
            [_S('NODE-10'), _S('SIMILAR')],
        ]),
        ('name', _S('NINE')),
        ('short_name', '9'),
        ('type', _S('NUM')),
    ]),
    (_S('NODE-10'), [
        ('value', 10),
        ('neighbors', [
            [_S('TIMES2-10'), _S('OPERAND')],
            [_S('TIMES3-10'), _S('OPERAND')],
            [_S('TIMES4-10'), _S('OPERAND')],
            [_S('TIMES5-10'), _S('OPERAND')],
            [_S('TIMES6-10'), _S('OPERAND')],
            [_S('TIMES7-10'), _S('OPERAND')],
            [_S('TIMES8-10'), _S('OPERAND')],
            [_S('TIMES9-10'), _S('OPERAND')],
            [_S('TIMES10-10'), _S('OPERAND')],
            [_S('TIMES10-15'), _S('OPERAND')],
            [_S('PLUS1-9'), _S('RESULT+')],
            [_S('PLUS2-8'), _S('RESULT+')],
            [_S('PLUS3-7'), _S('RESULT+')],
            [_S('PLUS4-6'), _S('RESULT+')],
            [_S('PLUS5-5'), _S('RESULT+')],
            [_S('PLUS5-10'), _S('RESULT+')],
            [_S('TIMES2-5'), _S('RESULTX')],
            [_S('NODE-9'), _S('SIMILAR')],
        ]),
        ('name', _S('TEN')),
        ('short_name', '10'),
        ('type', _S('NUM')),
    ]),
    (_S('NODE-12'), [
        ('value', 12),
        ('neighbors', [
            [_S('TIMES2-12'), _S('OPERAND')],
            [_S('NODE-15'), _S('SIMILAR')],
        ]),
        ('name', _S('TWELFE')),
        ('short_name', '12'),
        ('type', _S('NUM')),
    ]),
    (_S('NODE-15'), [
        ('value', 15),
        ('neighbors', [
            [_S('PLUS7-8'), _S('RESULT+')],
            [_S('PLUS5-10'), _S('RESULT+')],
            [_S('TIMES2-7'), _S('SIMILAR')],
            [_S('TIMES10-15'), _S('OPERAND')],
            [_S('NODE-12'), _S('SIMILAR')],
            [_S('NODE-16'), _S('SIMILAR')],
            [_S('NODE-20'), _S('SIMILAR')],
        ]),
        ('name', _S('FIFTEEN')),
        ('short_name', '15'),
        ('type', _S('NUM')),
    ]),
    (_S('NODE-16'), [
        ('value', 16),
        ('neighbors', [
            [_S('TIMES4-4'), _S('RESULTX')],
        ]),
        ('name', _S('SIXTEEN')),
        ('short_name', '16'),
        ('type', _S('NUM')),
    ]),
    (_S('NODE-20'), [
        ('value', 20),
        ('neighbors', [
            [_S('TIMES2-20'), _S('OPERAND')],
            [_S('TIMES3-20'), _S('OPERAND')],
            [_S('TIMES4-20'), _S('OPERAND')],
            [_S('TIMES5-20'), _S('OPERAND')],
            [_S('TIMES2-10'), _S('OPERAND')],
            [_S('NODE-15'), _S('SIMILAR')],
            [_S('NODE-25'), _S('SIMILAR')],
        ]),
        ('name', _S('TWENTY')),
        ('short_name', '20'),
        ('type', _S('NUM')),
    ]),
    (_S('NODE-25'), [
        ('value', 25),
        ('neighbors', [
            [_S('TIMES5-5'), _S('RESULTX')],
            [_S('TIMES2-12'), _S('SIMILAR')],
            [_S('NODE-20'), _S('SIMILAR')],
            [_S('NODE-30'), _S('SIMILAR')],
        ]),
        ('name', _S('TWENTY-FIVE')),
        ('short_name', '25'),
        ('type', _S('NUM')),
    ]),
    (_S('NODE-30'), [
        ('value', 30),
        ('neighbors', [
            [_S('TIMES3-10'), _S('RESULTX')],
            [_S('TIMES5-6'), _S('RESULTX')],
            [_S('NODE-25'), _S('SIMILAR')],
            [_S('NODE-40'), _S('SIMILAR')],
        ]),
        ('name', _S('THIRTY')),
        ('short_name', '30'),
        ('type', _S('NUM')),
    ]),
    (_S('NODE-40'), [
        ('value', 40),
        ('neighbors', [
            [_S('TIMES4-10'), _S('RESULTX')],
            [_S('TIMES2-20'), _S('RESULTX')],
            [_S('NODE-30'), _S('SIMILAR')],
            [_S('NODE-50'), _S('SIMILAR')],
        ]),
        ('name', _S('FOURTY')),
        ('short_name', '40'),
        ('type', _S('NUM')),
    ]),
    (_S('NODE-50'), [
        ('value', 50),
        ('neighbors', [
            [_S('TIMES5-10'), _S('RESULTX')],
            [_S('TIMES7-7'), _S('SIMILAR')],
            [_S('NODE-40'), _S('SIMILAR')],
            [_S('NODE-60'), _S('SIMILAR')],
        ]),
        ('name', _S('FIFTY')),
        ('short_name', '50'),
        ('type', _S('NUM')),
    ]),
    (_S('NODE-60'), [
        ('value', 60),
        ('neighbors', [
            [_S('TIMES6-10'), _S('RESULTX')],
            [_S('TIMES3-20'), _S('RESULTX')],
            [_S('NODE-50'), _S('SIMILAR')],
            [_S('NODE-70'), _S('SIMILAR')],
        ]),
        ('name', _S('SIXTY')),
        ('short_name', '60'),
        ('type', _S('NUM')),
    ]),
    (_S('NODE-70'), [
        ('value', 70),
        ('neighbors', [
            [_S('TIMES7-10'), _S('RESULTX')],
            [_S('NODE-60'), _S('SIMILAR')],
            [_S('NODE-80'), _S('SIMILAR')],
        ]),
        ('name', _S('SEVENTY')),
        ('short_name', '70'),
        ('type', _S('NUM')),
    ]),
    (_S('NODE-80'), [
        ('value', 80),
        ('neighbors', [
            [_S('TIMES8-10'), _S('RESULTX')],
            [_S('TIMES4-20'), _S('RESULTX')],
            [_S('NODE-70'), _S('SIMILAR')],
            [_S('NODE-81'), _S('SIMILAR')],
            [_S('NODE-90'), _S('SIMILAR')],
        ]),
        ('name', _S('EIGHTY')),
        ('short_name', '80'),
        ('type', _S('NUM')),
    ]),
    (_S('NODE-81'), [
        ('value', 81),
        ('neighbors', [
            [_S('TIMES9-9'), _S('RESULTX')],
            [_S('NODE-80'), _S('SIMILAR')],
        ]),
        ('name', _S('EIGHTY-ONE')),
        ('short_name', '81'),
        ('type', _S('NUM')),
    ]),
    (_S('NODE-90'), [
        ('value', 90),
        ('neighbors', [
            [_S('TIMES9-10'), _S('RESULTX')],
            [_S('NODE-80'), _S('SIMILAR')],
            [_S('NODE-100'), _S('SIMILAR')],
        ]),
        ('name', _S('NINETY')),
        ('short_name', '90'),
        ('type', _S('NUM')),
    ]),
    (_S('NODE-100'), [
        ('value', 100),
        ('neighbors', [
            [_S('TIMES10-10'), _S('RESULTX')],
            [_S('TIMES5-20'), _S('RESULTX')],
            [_S('NODE-90'), _S('SIMILAR')],
            [_S('NODE-150'), _S('SIMILAR')],
        ]),
        ('name', _S('ONE-HUNDRED')),
        ('short_name', '100'),
        ('type', _S('NUM')),
    ]),
    (_S('NODE-150'), [
        ('value', 150),
        ('neighbors', [
            [_S('TIMES10-15'), _S('RESULTX')],
            [_S('NODE-100'), _S('SIMILAR')],
        ]),
        ('name', _S('ONE-HUNDRED-FIFTY')),
        ('short_name', '150'),
        ('type', _S('NUM')),
    ]),
    (_S('NODE-MU10'), [
        ('neighbors', [
            [_S('NODE-10'), _S('INSTANCE')],
        ]),
        ('name', _S('MULTIPLE-OF-TEN')),
        ('short_name', 'mu10'),
    ]),
    (_S('NODE-MULTIPLY'), [
        ('neighbors', [
            [_S('NODE-ADD'), _S('OPERATION')],
            [_S('NODE-SUBTRACT'), _S('OPERATION')],
        ]),
        ('short_name', 'mult'),
        ('name', _S('MULTIPLY')),
    ]),
    (_S('NODE-ADD'), [
        ('neighbors', [
            [_S('NODE-MULTIPLY'), _S('OPERATION')],
            [_S('NODE-SUBTRACT'), _S('OPERATION')],
        ]),
        ('short_name', 'add'),
        ('name', _S('ADD')),
    ]),
    (_S('NODE-SUBTRACT'), [
        ('neighbors', [
            [_S('NODE-MULTIPLY'), _S('OPERATION')],
            [_S('NODE-ADD'), _S('OPERATION')],
        ]),
        ('short_name', 'sub'),
        ('name', _S('SUBTRACTION')),
        ('codelets', [[_S('LOOK-FOR-DIFF'), _S('%FIRST-THRESHOLD%'), _S('%FIRST-URGENCY%'), [0]]]),
    ]),
    (_S('PLUS1-1'), [
        ('neighbors', [
            [_S('NODE-1'), _S('RESULT+')],
            [_S('NODE-2'), _S('RESULT+')],
        ]),
        ('name', _S('PLUS1-1')),
        ('short_name', '1+1'),
        ('codelets', [[_S('LOOK-FOR-BL+'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [2, 1, 1]]]),
    ]),
    (_S('PLUS1-2'), [
        ('neighbors', [
            [_S('NODE-1'), _S('RESULT+')],
            [_S('NODE-2'), _S('RESULT+')],
            [_S('NODE-3'), _S('RESULT+')],
        ]),
        ('name', _S('PLUS1-2')),
        ('short_name', '1+2'),
        ('codelets', [[_S('LOOK-FOR-BL+'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [3, 1, 2]]]),
    ]),
    (_S('PLUS1-3'), [
        ('neighbors', [
            [_S('NODE-1'), _S('RESULT+')],
            [_S('NODE-3'), _S('RESULT+')],
            [_S('NODE-4'), _S('RESULT+')],
        ]),
        ('name', _S('PLUS1-3')),
        ('short_name', '1+3'),
        ('codelets', [[_S('LOOK-FOR-BL+'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [4, 1, 3]]]),
    ]),
    (_S('PLUS1-4'), [
        ('neighbors', [
            [_S('NODE-1'), _S('RESULT+')],
            [_S('NODE-4'), _S('RESULT+')],
            [_S('NODE-5'), _S('RESULT+')],
        ]),
        ('name', _S('PLUS1-4')),
        ('short_name', '1+4'),
        ('codelets', [[_S('LOOK-FOR-BL+'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [5, 1, 4]]]),
    ]),
    (_S('PLUS1-5'), [
        ('neighbors', [
            [_S('NODE-1'), _S('RESULT+')],
            [_S('NODE-5'), _S('RESULT+')],
            [_S('NODE-6'), _S('RESULT+')],
        ]),
        ('name', _S('PLUS1-5')),
        ('short_name', '1+5'),
        ('codelets', [[_S('LOOK-FOR-BL+'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [6, 1, 5]]]),
    ]),
    (_S('PLUS1-6'), [
        ('neighbors', [
            [_S('NODE-1'), _S('RESULT+')],
            [_S('NODE-6'), _S('RESULT+')],
            [_S('NODE-7'), _S('RESULT+')],
        ]),
        ('name', _S('PLUS1-6')),
        ('short_name', '1+6'),
        ('codelets', [[_S('LOOK-FOR-BL+'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [7, 1, 6]]]),
    ]),
    (_S('PLUS1-7'), [
        ('neighbors', [
            [_S('NODE-1'), _S('RESULT+')],
            [_S('NODE-7'), _S('RESULT+')],
            [_S('NODE-8'), _S('RESULT+')],
        ]),
        ('name', _S('PLUS1-7')),
        ('short_name', '1+7'),
        ('codelets', [[_S('LOOK-FOR-BL+'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [8, 1, 7]]]),
    ]),
    (_S('PLUS1-8'), [
        ('neighbors', [
            [_S('NODE-1'), _S('RESULT+')],
            [_S('NODE-8'), _S('RESULT+')],
            [_S('NODE-9'), _S('RESULT+')],
        ]),
        ('name', _S('PLUS1-8')),
        ('short_name', '1+8'),
        ('codelets', [[_S('LOOK-FOR-BL+'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [9, 1, 8]]]),
    ]),
    (_S('PLUS1-9'), [
        ('neighbors', [
            [_S('NODE-1'), _S('RESULT+')],
            [_S('NODE-9'), _S('RESULT+')],
            [_S('NODE-10'), _S('RESULT+')],
        ]),
        ('name', _S('PLUS1-9')),
        ('short_name', '1+9'),
        ('codelets', [[_S('LOOK-FOR-BL+'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [10, 1, 9]]]),
    ]),
    (_S('PLUS2-2'), [
        ('neighbors', [
            [_S('NODE-2'), _S('RESULT+')],
            [_S('NODE-4'), _S('RESULT+')],
        ]),
        ('name', _S('PLUS2-2')),
        ('short_name', '2+2'),
        ('codelets', [[_S('LOOK-FOR-BL+'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [4, 2, 2]]]),
    ]),
    (_S('PLUS2-3'), [
        ('neighbors', [
            [_S('NODE-2'), _S('RESULT+')],
            [_S('NODE-3'), _S('RESULT+')],
            [_S('NODE-5'), _S('RESULT+')],
        ]),
        ('name', _S('PLUS2-3')),
        ('short_name', '2+3'),
        ('codelets', [[_S('LOOK-FOR-BL+'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [5, 2, 3]]]),
    ]),
    (_S('PLUS2-4'), [
        ('neighbors', [
            [_S('NODE-2'), _S('RESULT+')],
            [_S('NODE-4'), _S('RESULT+')],
            [_S('NODE-6'), _S('RESULT+')],
        ]),
        ('name', _S('PLUS2-4')),
        ('short_name', '2+4'),
        ('codelets', [[_S('LOOK-FOR-BL+'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [6, 2, 4]]]),
    ]),
    (_S('PLUS2-5'), [
        ('neighbors', [
            [_S('NODE-2'), _S('RESULT+')],
            [_S('NODE-5'), _S('RESULT+')],
            [_S('NODE-7'), _S('RESULT+')],
        ]),
        ('name', _S('PLUS2-5')),
        ('short_name', '2+5'),
        ('codelets', [[_S('LOOK-FOR-BL+'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [7, 2, 5]]]),
    ]),
    (_S('PLUS2-6'), [
        ('neighbors', [
            [_S('NODE-2'), _S('RESULT+')],
            [_S('NODE-6'), _S('RESULT+')],
            [_S('NODE-8'), _S('RESULT+')],
        ]),
        ('name', _S('PLUS2-6')),
        ('short_name', '2+6'),
        ('codelets', [[_S('LOOK-FOR-BL+'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [8, 2, 6]]]),
    ]),
    (_S('PLUS2-7'), [
        ('neighbors', [
            [_S('NODE-2'), _S('RESULT+')],
            [_S('NODE-7'), _S('RESULT+')],
            [_S('NODE-9'), _S('RESULT+')],
        ]),
        ('name', _S('PLUS2-7')),
        ('short_name', '2+7'),
        ('codelets', [[_S('LOOK-FOR-BL+'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [9, 2, 7]]]),
    ]),
    (_S('PLUS2-8'), [
        ('neighbors', [
            [_S('NODE-2'), _S('RESULT+')],
            [_S('NODE-8'), _S('RESULT+')],
            [_S('NODE-10'), _S('RESULT+')],
        ]),
        ('name', _S('PLUS2-8')),
        ('short_name', '2+8'),
        ('codelets', [[_S('LOOK-FOR-BL+'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [10, 2, 8]]]),
    ]),
    (_S('PLUS3-3'), [
        ('neighbors', [
            [_S('NODE-3'), _S('RESULT+')],
            [_S('NODE-6'), _S('RESULT+')],
        ]),
        ('name', _S('PLUS3-3')),
        ('short_name', '3+3'),
        ('codelets', [[_S('LOOK-FOR-BL+'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [6, 3, 3]]]),
    ]),
    (_S('PLUS3-4'), [
        ('neighbors', [
            [_S('NODE-3'), _S('RESULT+')],
            [_S('NODE-4'), _S('RESULT+')],
            [_S('NODE-7'), _S('RESULT+')],
        ]),
        ('name', _S('PLUS3-4')),
        ('short_name', '3+4'),
        ('codelets', [[_S('LOOK-FOR-BL+'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [7, 3, 4]]]),
    ]),
    (_S('PLUS3-5'), [
        ('neighbors', [
            [_S('NODE-3'), _S('RESULT+')],
            [_S('NODE-5'), _S('RESULT+')],
            [_S('NODE-8'), _S('RESULT+')],
        ]),
        ('name', _S('PLUS3-5')),
        ('short_name', '3+5'),
        ('codelets', [[_S('LOOK-FOR-BL+'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [8, 3, 5]]]),
    ]),
    (_S('PLUS3-6'), [
        ('neighbors', [
            [_S('NODE-3'), _S('RESULT+')],
            [_S('NODE-6'), _S('RESULT+')],
            [_S('NODE-9'), _S('RESULT+')],
        ]),
        ('name', _S('PLUS3-6')),
        ('short_name', '3+6'),
        ('codelets', [[_S('LOOK-FOR-BL+'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [9, 3, 6]]]),
    ]),
    (_S('PLUS3-7'), [
        ('neighbors', [
            [_S('NODE-3'), _S('RESULT+')],
            [_S('NODE-7'), _S('RESULT+')],
            [_S('NODE-10'), _S('RESULT+')],
        ]),
        ('name', _S('PLUS3-7')),
        ('short_name', '3+7'),
        ('codelets', [[_S('LOOK-FOR-BL+'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [10, 3, 7]]]),
    ]),
    (_S('PLUS4-4'), [
        ('neighbors', [
            [_S('NODE-4'), _S('RESULT+')],
            [_S('NODE-8'), _S('RESULT+')],
        ]),
        ('name', _S('PLUS4-4')),
        ('short_name', '4+4'),
        ('codelets', [[_S('LOOK-FOR-BL+'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [8, 4, 4]]]),
    ]),
    (_S('PLUS4-5'), [
        ('neighbors', [
            [_S('NODE-4'), _S('RESULT+')],
            [_S('NODE-5'), _S('RESULT+')],
            [_S('NODE-9'), _S('RESULT+')],
        ]),
        ('name', _S('PLUS4-5')),
        ('short_name', '4+5'),
        ('codelets', [[_S('LOOK-FOR-BL+'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [9, 4, 5]]]),
    ]),
    (_S('PLUS4-6'), [
        ('neighbors', [
            [_S('NODE-4'), _S('RESULT+')],
            [_S('NODE-6'), _S('RESULT+')],
            [_S('NODE-10'), _S('RESULT+')],
        ]),
        ('name', _S('PLUS4-6')),
        ('short_name', '4+6'),
        ('codelets', [[_S('LOOK-FOR-BL+'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [10, 4, 6]]]),
    ]),
    (_S('PLUS5-5'), [
        ('neighbors', [
            [_S('NODE-5'), _S('RESULT+')],
            [_S('NODE-10'), _S('RESULT+')],
        ]),
        ('name', _S('PLUS5-5')),
        ('short_name', '5+5'),
        ('codelets', [[_S('LOOK-FOR-BL+'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [10, 5, 5]]]),
    ]),
    (_S('PLUS7-8'), [
        ('neighbors', [
            [_S('NODE-7'), _S('RESULT+')],
            [_S('NODE-8'), _S('RESULT+')],
            [_S('NODE-15'), _S('RESULT+')],
        ]),
        ('name', _S('PLUS7-8')),
        ('short_name', '7+8'),
        ('codelets', [[_S('LOOK-FOR-BL+'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [15, 7, 8]]]),
    ]),
    (_S('PLUS5-10'), [
        ('neighbors', [
            [_S('NODE-5'), _S('RESULT+')],
            [_S('NODE-10'), _S('RESULT+')],
            [_S('NODE-15'), _S('RESULT+')],
        ]),
        ('name', _S('PLUS5-10')),
        ('short_name', '5+10'),
        ('codelets', [[_S('LOOK-FOR-BL+'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [15, 5, 10]]]),
    ]),
    (_S('TIMES2-2'), [
        ('neighbors', [
            [_S('NODE-2'), _S('OPERAND')],
            [_S('NODE-4'), _S('RESULTX')],
        ]),
        ('name', _S('TIMES2-2')),
        ('short_name', '2x2'),
        ('codelets', [[_S('LOOK-FOR-BLX'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [4, 2, 2]]]),
    ]),
    (_S('TIMES2-3'), [
        ('neighbors', [
            [_S('NODE-2'), _S('OPERAND')],
            [_S('NODE-3'), _S('OPERAND')],
            [_S('NODE-6'), _S('RESULTX')],
        ]),
        ('name', _S('TIMES2-3')),
        ('short_name', '2x3'),
        ('codelets', [[_S('LOOK-FOR-BLX'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [6, 2, 3]]]),
    ]),
    (_S('TIMES2-4'), [
        ('neighbors', [
            [_S('NODE-2'), _S('OPERAND')],
            [_S('NODE-4'), _S('OPERAND')],
            [_S('NODE-8'), _S('RESULTX')],
        ]),
        ('name', _S('TIMES2-4')),
        ('short_name', '2x4'),
        ('codelets', [[_S('LOOK-FOR-BLX'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [8, 2, 4]]]),
    ]),
    (_S('TIMES2-5'), [
        ('neighbors', [
            [_S('NODE-2'), _S('OPERAND')],
            [_S('NODE-5'), _S('OPERAND')],
            [_S('NODE-10'), _S('RESULTX')],
        ]),
        ('name', _S('TIMES2-5')),
        ('short_name', '2x5'),
        ('codelets', [[_S('LOOK-FOR-BLX'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [10, 2, 5]]]),
    ]),
    (_S('TIMES2-7'), [
        ('neighbors', [
            [_S('NODE-2'), _S('OPERAND')],
            [_S('NODE-7'), _S('OPERAND')],
            [_S('NODE-15'), _S('SIMILAR')],
        ]),
        ('name', _S('TIMES2-7')),
        ('short_name', '2x7'),
        ('codelets', [[_S('LOOK-FOR-BLX'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [15, 2, 7]]]),
    ]),
    (_S('TIMES2-10'), [
        ('neighbors', [
            [_S('NODE-2'), _S('OPERAND')],
            [_S('NODE-10'), _S('OPERAND')],
            [_S('NODE-20'), _S('RESULTX')],
        ]),
        ('name', _S('TIMES2-10')),
        ('short_name', '2x10'),
        ('codelets', [[_S('LOOK-FOR-BLX'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [20, 2, 10]]]),
    ]),
    (_S('TIMES2-12'), [
        ('neighbors', [
            [_S('NODE-2'), _S('OPERAND')],
            [_S('NODE-12'), _S('OPERAND')],
            [_S('NODE-25'), _S('SIMILAR')],
        ]),
        ('name', _S('TIMES2-12')),
        ('short_name', '2x12'),
        ('codelets', [[_S('LOOK-FOR-BLX'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [24, 2, 12]]]),
    ]),
    (_S('TIMES2-20'), [
        ('neighbors', [
            [_S('NODE-2'), _S('OPERAND')],
            [_S('NODE-20'), _S('OPERAND')],
            [_S('NODE-40'), _S('RESULTX')],
        ]),
        ('name', _S('TIMES2-20')),
        ('short_name', '2x20'),
        ('codelets', [[_S('LOOK-FOR-BLX'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [40, 2, 20]]]),
    ]),
    (_S('TIMES3-3'), [
        ('neighbors', [
            [_S('NODE-3'), _S('OPERAND')],
            [_S('NODE-9'), _S('RESULTX')],
        ]),
        ('name', _S('TIMES3-3')),
        ('short_name', '3x3'),
        ('codelets', [[_S('LOOK-FOR-BLX'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [9, 3, 3]]]),
    ]),
    (_S('TIMES3-10'), [
        ('neighbors', [
            [_S('NODE-3'), _S('OPERAND')],
            [_S('NODE-10'), _S('OPERAND')],
            [_S('NODE-30'), _S('RESULTX')],
        ]),
        ('name', _S('TIMES3-10')),
        ('short_name', '3x10'),
        ('codelets', [[_S('LOOK-FOR-BLX'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [30, 3, 10]]]),
    ]),
    (_S('TIMES3-20'), [
        ('neighbors', [
            [_S('NODE-3'), _S('OPERAND')],
            [_S('NODE-20'), _S('OPERAND')],
            [_S('NODE-60'), _S('RESULTX')],
        ]),
        ('name', _S('TIMES3-20')),
        ('short_name', '3x20'),
        ('codelets', [[_S('LOOK-FOR-BLX'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [60, 3, 20]]]),
    ]),
    (_S('TIMES4-4'), [
        ('neighbors', [
            [_S('NODE-4'), _S('OPERAND')],
            [_S('NODE-16'), _S('RESULTX')],
        ]),
        ('name', _S('TIMES4-4')),
        ('short_name', '4x4'),
        ('codelets', [[_S('LOOK-FOR-BLX'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [16, 4, 4]]]),
    ]),
    (_S('TIMES4-10'), [
        ('neighbors', [
            [_S('NODE-4'), _S('OPERAND')],
            [_S('NODE-10'), _S('OPERAND')],
            [_S('NODE-40'), _S('RESULTX')],
        ]),
        ('name', _S('TIMES4-10')),
        ('short_name', '4x10'),
        ('codelets', [[_S('LOOK-FOR-BLX'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [40, 4, 10]]]),
    ]),
    (_S('TIMES4-20'), [
        ('neighbors', [
            [_S('NODE-4'), _S('OPERAND')],
            [_S('NODE-20'), _S('OPERAND')],
            [_S('NODE-80'), _S('RESULTX')],
        ]),
        ('name', _S('TIMES4-20')),
        ('short_name', '4x20'),
        ('codelets', [[_S('LOOK-FOR-BLX'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [80, 4, 20]]]),
    ]),
    (_S('TIMES5-5'), [
        ('neighbors', [
            [_S('NODE-5'), _S('OPERAND')],
            [_S('NODE-25'), _S('RESULTX')],
        ]),
        ('name', _S('TIMES5-5')),
        ('short_name', '5x5'),
        ('codelets', [[_S('LOOK-FOR-BLX'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [25, 5, 5]]]),
    ]),
    (_S('TIMES5-6'), [
        ('neighbors', [
            [_S('NODE-5'), _S('OPERAND')],
            [_S('NODE-6'), _S('OPERAND')],
            [_S('NODE-30'), _S('RESULTX')],
        ]),
        ('name', _S('TIMES5-6')),
        ('short_name', '5x6'),
        ('codelets', [[_S('LOOK-FOR-BLX'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [30, 5, 6]]]),
    ]),
    (_S('TIMES5-10'), [
        ('neighbors', [
            [_S('NODE-5'), _S('OPERAND')],
            [_S('NODE-10'), _S('OPERAND')],
            [_S('NODE-50'), _S('RESULTX')],
        ]),
        ('name', _S('TIMES5-10')),
        ('short_name', '5x10'),
        ('codelets', [[_S('LOOK-FOR-BLX'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [50, 5, 10]]]),
    ]),
    (_S('TIMES5-20'), [
        ('neighbors', [
            [_S('NODE-5'), _S('OPERAND')],
            [_S('NODE-20'), _S('OPERAND')],
            [_S('NODE-100'), _S('RESULTX')],
        ]),
        ('name', _S('TIMES5-20')),
        ('short_name', '5x20'),
        ('codelets', [[_S('LOOK-FOR-BLX'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [100, 5, 20]]]),
    ]),
    (_S('TIMES6-10'), [
        ('neighbors', [
            [_S('NODE-6'), _S('OPERAND')],
            [_S('NODE-10'), _S('OPERAND')],
            [_S('NODE-60'), _S('RESULTX')],
        ]),
        ('name', _S('TIMES6-10')),
        ('short_name', '6x10'),
        ('codelets', [[_S('LOOK-FOR-BLX'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [60, 6, 10]]]),
    ]),
    (_S('TIMES7-7'), [
        ('neighbors', [
            [_S('NODE-7'), _S('OPERAND')],
            [_S('NODE-50'), _S('SIMILAR')],
        ]),
        ('name', _S('TIMES7-7')),
        ('short_name', '7x7'),
        ('codelets', [[_S('LOOK-FOR-BLX'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [49, 7, 7]]]),
    ]),
    (_S('TIMES7-10'), [
        ('neighbors', [
            [_S('NODE-7'), _S('OPERAND')],
            [_S('NODE-10'), _S('OPERAND')],
            [_S('NODE-70'), _S('RESULTX')],
        ]),
        ('name', _S('TIMES7-10')),
        ('short_name', '7x10'),
        ('codelets', [[_S('LOOK-FOR-BLX'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [70, 7, 10]]]),
    ]),
    (_S('TIMES8-10'), [
        ('neighbors', [
            [_S('NODE-8'), _S('OPERAND')],
            [_S('NODE-10'), _S('OPERAND')],
            [_S('NODE-80'), _S('RESULTX')],
        ]),
        ('name', _S('TIMES8-10')),
        ('short_name', '8x10'),
        ('codelets', [[_S('LOOK-FOR-BLX'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [80, 8, 10]]]),
    ]),
    (_S('TIMES9-9'), [
        ('neighbors', [
            [_S('NODE-9'), _S('OPERAND')],
            [_S('NODE-81'), _S('RESULTX')],
        ]),
        ('name', _S('TIMES9-9')),
        ('short_name', '9x9'),
        ('codelets', [[_S('LOOK-FOR-BLX'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [81, 9, 9]]]),
    ]),
    (_S('TIMES9-10'), [
        ('neighbors', [
            [_S('NODE-9'), _S('OPERAND')],
            [_S('NODE-10'), _S('OPERAND')],
            [_S('NODE-90'), _S('RESULTX')],
        ]),
        ('name', _S('TIMES9-10')),
        ('short_name', '9x10'),
        ('codelets', [[_S('LOOK-FOR-BLX'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [90, 9, 10]]]),
    ]),
    (_S('TIMES10-10'), [
        ('neighbors', [
            [_S('NODE-10'), _S('OPERAND')],
            [_S('NODE-100'), _S('RESULTX')],
        ]),
        ('name', _S('TIMES10-10')),
        ('short_name', '10x10'),
        ('codelets', [[_S('LOOK-FOR-BLX'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [100, 10, 10]]]),
    ]),
    (_S('TIMES10-15'), [
        ('neighbors', [
            [_S('NODE-10'), _S('OPERAND')],
            [_S('NODE-15'), _S('OPERAND')],
            [_S('NODE-150'), _S('RESULTX')],
        ]),
        ('name', _S('TIMES10-15')),
        ('short_name', '10x15'),
        ('codelets', [[_S('LOOK-FOR-BLX'), _S('%FIRST-THRESHOLD%'), _S('%SECOND-URGENCY%'), [150, 10, 15]]]),
    ]),
    (_S('OPERAND'), [
        ('name', _S('OPERAND')),
        ('short_name', 'operd'),
    ]),
    (_S('RESULT+'), [
        ('name', _S('RESULT+')),
        ('short_name', 'resl+'),
    ]),
    (_S('RESULTX'), [
        ('name', _S('RESULTX')),
        ('short_name', 'reslx'),
    ]),
    (_S('SIMILAR'), [
        ('name', _S('SIMILAR')),
        ('short_name', 'simil'),
    ]),
    (_S('OPERATION'), [
        ('name', _S('OPERATION')),
        ('short_name', 'opion'),
    ]),
    (_S('INSTANCE'), [
        ('name', _S('INSTANCE')),
        ('short_name', 'inst'),
    ]),
    (_S('PLUS'), [
        ('name', _S('PLUS')),
        ('short_name', 'plus'),
    ]),
    (_S('MINUS'), [
        ('name', _S('MINUS')),
        ('short_name', 'diff'),
    ]),
    (_S('TIMES'), [
        ('name', _S('TIMES')),
        ('short_name', 'prod'),
    ]),
]

# The top-level (setq *pnet* (list ...)): the 88 holders, in order.
PNET = [
    _S('NODE-1'), _S('NODE-2'), _S('NODE-3'), _S('NODE-4'), _S('NODE-5'), _S('NODE-6'),
    _S('NODE-7'), _S('NODE-8'), _S('NODE-9'), _S('NODE-10'), _S('NODE-12'), _S('NODE-15'),
    _S('NODE-16'), _S('NODE-20'), _S('NODE-25'), _S('NODE-30'), _S('NODE-40'), _S('NODE-50'),
    _S('NODE-60'), _S('NODE-70'), _S('NODE-80'), _S('NODE-81'), _S('NODE-90'), _S('NODE-100'),
    _S('NODE-150'), _S('PLUS1-1'), _S('PLUS1-2'), _S('PLUS1-3'), _S('PLUS1-4'), _S('PLUS1-5'),
    _S('PLUS1-6'), _S('PLUS1-7'), _S('PLUS1-8'), _S('PLUS1-9'), _S('PLUS2-2'), _S('PLUS2-3'),
    _S('PLUS2-4'), _S('PLUS2-5'), _S('PLUS2-6'), _S('PLUS2-7'), _S('PLUS2-8'), _S('PLUS3-3'),
    _S('PLUS3-4'), _S('PLUS3-5'), _S('PLUS3-6'), _S('PLUS3-7'), _S('PLUS4-4'), _S('PLUS4-5'),
    _S('PLUS4-6'), _S('PLUS5-5'), _S('PLUS5-10'), _S('PLUS7-8'), _S('TIMES2-2'), _S('TIMES2-3'),
    _S('TIMES2-4'), _S('TIMES2-5'), _S('TIMES2-7'), _S('TIMES2-10'), _S('TIMES2-12'), _S('TIMES2-20'),
    _S('TIMES3-3'), _S('TIMES3-10'), _S('TIMES3-20'), _S('TIMES4-4'), _S('TIMES4-10'), _S('TIMES4-20'),
    _S('TIMES5-5'), _S('TIMES5-6'), _S('TIMES5-10'), _S('TIMES5-20'), _S('TIMES6-10'), _S('TIMES7-7'),
    _S('TIMES7-10'), _S('TIMES8-10'), _S('TIMES9-9'), _S('TIMES9-10'), _S('TIMES10-10'), _S('TIMES10-15'),
    _S('NODE-MU10'), _S('NODE-MULTIPLY'), _S('NODE-ADD'), _S('NODE-SUBTRACT'), _S('OPERAND'), _S('RESULT+'),
    _S('RESULTX'), _S('SIMILAR'), _S('OPERATION'), _S('INSTANCE'),
]

# --- END GENERATED ---
