(try-cat 'n) (printf "~s~%" (lookup-list 'n *scratchspace*))
(try-cat 'n) (printf "~s~%" (lookup-list 'n *scratchspace*))
(try-cat 'n) (printf "~s~%" (lookup-list 'n *scratchspace*))
(try-cat 'n) (printf "~s~%" (lookup-list 'n *scratchspace*))
(try-cat 'n) (printf "~s~%" (lookup-list 'n *scratchspace*))
(try-cat 'n) (printf "~s~%" (lookup-list 'n *scratchspace*))
(try-cat 'n) (printf "~s~%" (lookup-list 'n *scratchspace*))
(try-cat 'n) (printf "~s~%" (lookup-list 'n *scratchspace*))
(try-cat 'n) (printf "~s~%" (lookup-list 'n *scratchspace*))
(try-cat 'n) (printf "~s~%" (lookup-list 'n *scratchspace*))
(try-cat 'n) (printf "~s~%" (lookup-list 'n *scratchspace*))
(try-cat 'n) (printf "~s~%" (lookup-list 'n *scratchspace*))
(try-cat 'n) (printf "~s~%" (lookup-list 'n *scratchspace*))
(try-cat 'n) (printf "~s~%" (lookup-list 'n *scratchspace*))
(try-cat 'n) (printf "~s~%" (lookup-list 'n *scratchspace*))
(try-cat 'n) (printf "~s~%" (lookup-list 'n *scratchspace*))
(try-cat 'n) (printf "~s~%" (lookup-list 'n *scratchspace*))
(try-cat 'n) (printf "~s~%" (lookup-list 'n *scratchspace*))
(try-cat 'n) (printf "~s~%" (lookup-list 'n *scratchspace*))
(try-cat 'n) (printf "~s~%" (lookup-list 'n *scratchspace*))
(try-cat 'n) (printf "~s~%" (lookup-list 'n *scratchspace*))
(try-cat 'n) (printf "~s~%" (lookup-list 'n *scratchspace*))
(try-cat 'n) (printf "~s~%" (lookup-list 'n *scratchspace*))
(try-cat 'n) (printf "~s~%" (lookup-list 'n *scratchspace*))
(try-cat 'n) (printf "~s~%" (lookup-list 'n *scratchspace*))
(try-cat 'n) (printf "~s~%" (lookup-list 'n *scratchspace*))
(try-cat 'n) (printf "~s~%" (lookup-list 'n *scratchspace*))
(try-cat 'n) (printf "~s~%" (lookup-list 'n *scratchspace*))
(try-cat 'n) (printf "~s~%" (lookup-list 'n *scratchspace*))
(try-cat 'n) (printf "~s~%" (lookup-list 'n *scratchspace*))

((5 22 23 25 36)
 (55.777)
 (((23 25 36 49) (44.538 49.4885 100000.0 43.229))
  ((9 20 21 23 25 48 49) (100000.0))
  ((8 36 39 49) (100000.0))
  (() (100000.0))) 3)
((23 36 39 49) (49.537)
 (((5 22 23 25 36) (55.777))
  ((23 25 36 49) (44.538 49.4885 100000.0 43.229))
  ((9 20 21 23 25 48 49) (100000.0))
  ((8 36 39 49) (100000.0))
  (() (100000.0)))
 3)

