//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RhythmCat {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300, 350")]
        public global::System.Drawing.Size coderackSize {
            get {
                return ((global::System.Drawing.Size)(this["coderackSize"]));
            }
            set {
                this["coderackSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1113, 10")]
        public global::System.Drawing.Point coderackLoc {
            get {
                return ((global::System.Drawing.Point)(this["coderackLoc"]));
            }
            set {
                this["coderackLoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1113, 360")]
        public global::System.Drawing.Point groupScoresLoc {
            get {
                return ((global::System.Drawing.Point)(this["groupScoresLoc"]));
            }
            set {
                this["groupScoresLoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300, 300")]
        public global::System.Drawing.Size groupScoresSize {
            get {
                return ((global::System.Drawing.Size)(this["groupScoresSize"]));
            }
            set {
                this["groupScoresSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 10")]
        public global::System.Drawing.Point workspaceLoc {
            get {
                return ((global::System.Drawing.Point)(this["workspaceLoc"]));
            }
            set {
                this["workspaceLoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1103, 722")]
        public global::System.Drawing.Size workspaceSize {
            get {
                return ((global::System.Drawing.Size)(this["workspaceSize"]));
            }
            set {
                this["workspaceSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1113, 660")]
        public global::System.Drawing.Point mainLoc {
            get {
                return ((global::System.Drawing.Point)(this["mainLoc"]));
            }
            set {
                this["mainLoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300, 300")]
        public global::System.Drawing.Size mainSize {
            get {
                return ((global::System.Drawing.Size)(this["mainSize"]));
            }
            set {
                this["mainSize"] = value;
            }
        }
    }
}
